// my-angular-portfolio/src/app/components/testimonial/testimonial.component.ts
// src/app/components/testimonial/testimonial.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-testimonial',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './testimonial.component.html',
  styleUrls: ['./testimonial.component.css'],
})
export class TestimonialComponent {
  testimonial = {
    quote:
      "Without Journey Commerce, we would never have been able to implement this system ourselves. They have a great team and they are always enough hours in the day to make sure we make our goals. I can't recommend them highly enough, you're in great hands.",
    author: 'Dhimmo Reijnder',
    title: 'Founder',
  };
}

<div class="testimonial-card">
  <p class="quote">“{{ testimonial.quote }}”</p>
  <div class="author-info">
    <img src="assets/images/dhimmo-reijnder.jpg" alt="Dhimmo Reijnder" class="author-img">
    <div>
      <strong class="author-name">{{ testimonial.author }}</strong>
      <span class="author-title">{{ testimonial.title }}</span>
    </div>
  </div>
</div>

// js/react-testimonial.js
// js/react-testimonials.js

function TestimonialCard(props) {
  return (
    <div className="card">
      <p>“{props.quote}”</p>
      <strong>– {props.author}</strong>
    </div>
  );
}

function TestimonialSection() {
  const testimonialData = {
    quote:
      "Without Journey Commerce, we would never have been able to implement this system ourselves...",
    author: "Dhimmo Reijnder, Founder",
  };

  return (
    <TestimonialCard
      quote={testimonialData.quote}
      author={testimonialData.author}
    />
  );
}

const testimonialContainer = document.querySelector(
  "#react-testimonial-container"
);
if (testimonialContainer) {
  const root = ReactDOM.createRoot(testimonialContainer);
  root.render(<TestimonialSection />);
}
